Support pulling image from components
Elektrobit/flake-pilot pull request #102
Opened 2023-05-19 13:37 UTC by schaefi

So far pulling a firecracker image was limited to the KIWI kis image type. With this commit it's also possible to pull an image from it's components; rootfs, kernel and optional initrd. This allows for example to make use of the firecracker hosted CI images or any other rootfs image in combination with some kernel/initrd. During the pull of such an image there is also a check for the sci binary inside of the rootfs. If it does not exist it gets added to the rootfs such that the firecracker-pilot can work with it. This Fixes #99

2023-05-19 13:39 UTC, schaefi commented
@m-kat with the change here the following becomes possible

```
flake-ctl firecracker pull \
    --rootfs https://s3.amazonaws.com/spec.ccfc.min/ci-artifacts/disks/x86_64/ubuntu-18.04.ext4 \
    --kernel https://s3.amazonaws.com/spec.ccfc.min/img/quickstart_guide/x86_64/kernels/vmlinux.bin \
    --name firecore --force
flake-ctl firecracker register --app /home/ms/mybash --target /bin/bash --vm firecore
```

Requires the PR from here #101 to be applied

2023-05-19 13:57 UTC, schaefi commented
@m-kat please note I'm shelling out for mount/umount and copy because they get called through sudo such that a normal user can perform the pull action and only discrete commands that requires root permissions are called through
sudo. Thanks

2023-05-22 07:12 UTC, m-kat requested changes
After I  read your explanations in the comments it looks good, Pls just document public functions in the code

2023-05-22 07:12 UTC, m-kat commented on flake-ctl/src/firecracker.rs
> +pub async fn pull_component_image(
Please add documentation to each public function

2023-05-22 08:58 UTC, m-kat commented on flake-ctl/src/firecracker.rs
> +pub async fn pull_component_image(
Ok the git wrapped the lines with the comments in my view ;-)

2023-05-22 14:03 UTC, merged