Replace adhoc yaml with serde
Elektrobit/flake-pilot pull request #131
Opened 2023-07-24 20:26 UTC by Ichmed

first part of https://github.com/Elektrobit/flake-pilot/issues/128

Includes only podman config, will copy the approach for firecracker and/or create generic version for all back ends if approved

Adds lazy_static for config initialization, can be removed if rust version is bumped to one that includes [OnceCell](https://doc.rust-lang.org/stable/std/cell/struct.OnceCell.html)

2023-07-25 09:26 UTC, Ichmed commented
I had to adjust the config slightly because apparently `rust_yaml` and `serde_yaml` treat the ~ slightly differently (this version wanted to use the user "~" instead of the default user)

2023-07-26 07:35 UTC, schaefi commented
Great this is a good pull request to review and test, thanks much :+1: I will take a closer look and test at the end of the week. Until then my plate is full with other stuff. On a first look it really looks good, again thanks much appreciated

2023-07-28 07:44 UTC, schaefi requested changes
I tested the change and it works for me but I think we are loosing an important feature, see my comments. Thanks

2023-07-28 07:58 UTC, Ichmed commented on podman-pilot/src/main.rs
> -    let runtime_config = app_path::program_config(&program_name);
Oh completely forgot about that, i saw that in the docs but could not see how it was implemented in the code. The old code read in all the yamls and then only ever accessed the first one, am I missing something?

2023-07-28 09:23 UTC, Ichmed commented on podman-pilot/src/main.rs
> -    let runtime_config = app_path::program_config(&program_name);
Oh, it appended the dicts to each other so the keys get overridden, now i get it. I thought it built a Vec with one Yaml after the other, I'll try the same thing with serde_yaml.

2023-07-28 15:25 UTC, Ichmed commented
Re-added yaml unification and added a unit test for it.
Had to use yaml-rust since serde_yaml does not support identical keys since version 0.9. We should probably still figure out a better solution for unification but that is out of the scope of this PR

2023-08-02 09:27 UTC, schaefi commented on podman-pilot/src/config.rs
> +fn load_config() -> Config<'static> {
Would you mind to keep the comment that explains the reading and structure of our config files in this method ? I'm referencing the comment that you can see in the deleted ```program_config``` method ?

Would be great, thanks

2023-08-07 11:16 UTC, schaefi approved these changes
Looks good now, thanks for your effort :+1:

2023-08-07 11:19 UTC, merged