Reactivate binary stripping
Elektrobit/flake-pilot pull request #153
Opened 2023-08-22 11:55 UTC by isbm

If there is no any particular reasons why we should not remove symbols information, then this should be activated back.

2023-08-22 12:14 UTC, Ichmed commented
This is not due to the changes done here, but `cargo build` ignores profiles not defined in the top level cargo file

Since the release profiles are identical anyway the individual ones should be removed and replaced with one in the top Cargo.toml

2023-08-22 12:16 UTC, Ichmed commented
I'm seconding removing the upx step since, afaik, it does not change binary size during runtime but only on disk.

Startup time is much more valuable then disk space (especially because many flakes may be starting at once while there will be only on pilot binary on disk)

2023-08-22 12:18 UTC, Ichmed requested changes

2023-08-22 12:18 UTC, Ichmed commented on firecracker-pilot/firecracker-service/service-communication/Cargo.toml
>  [profile.release]
Move all profiles to the top level Cargo.toml

2023-08-25 08:32 UTC, schaefi commented on firecracker-pilot/firecracker-service/service-communication/Cargo.toml
>  [profile.release]
yep would be good if along with this change all ```[profile.xxx]``` sections could be moved to the toplevel Cargo.toml. Messages like

```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
```

will go away then

Thanks

2023-08-28 16:38 UTC, Ichmed commented
LGTM

2023-08-28 16:42 UTC, merged