Refactor port allocation for UDS socket
Elektrobit/flake-pilot pull request #154
Opened 2023-08-22 21:30 UTC by schaefi

When using the firecracker-pilot in a resume type flake, the pilot creates a UDS socket for listening on data. Each of this socket connections requires a free port. The former implementation selects the socket by a random number within a given range. However, this is not a stable solution and the risk to select an already occupied port is high. This commit refactors the port allocation to a simple increment by one starting at FIRECRACKER_VSOCK_PORT_START. If the port is free is checked by looking up the port number of occupied ports which is encoded in the firecracker-pilot created UDS socket filenames. This selection for a free port is also not completely stable as there could be other services on the OS that occupies the selected port for which firecracker-pilot has no information. Further conversations on this topic brought up some ideas how to select a system wide free port by e.g a kernel module but as a first improvement to the former implementation this commit should serve the purpose.

This Fixes #114

2023-08-23 07:08 UTC, schaefi commented
I think there might be even a simpler solution... testing it

2023-08-23 08:18 UTC, Ichmed commented
Looks good apart from my comment, definitely more robust than random ports and also way faster then looping through filenames.

2023-08-23 08:38 UTC, schaefi commented
> Looks good apart from my comment, definitely more robust than random ports and also way faster then looping through filenames.

Thanks, so if you are fine with it I'll wait for approval prior merge :)

I would also be interested what happens behind the scene, as you mentioned a kernel module for getting a system wide free port through a semaphore I was curious to see if there is some code, poc or something available. You mentioned @m-kat is working on that but it seems there is not much sharing on this activity on the opensource side of things. So if there is anything you can share I would be interested. Thanks

2023-08-23 08:49 UTC, Ichmed approved these changes

2023-08-23 09:35 UTC, schaefi commented on firecracker-pilot/src/firecracker.rs
> +    let port = defaults::FIRECRACKER_VSOCK_PORT_START + id();
yes good point, thinking about it

2023-08-24 09:39 UTC, isbm requested changes
Doesn't LGTM.

2023-08-24 09:44 UTC, isbm commented
I would be voting against this solution. Current random solution is bad enough to be considered improved, but it still works by far anyhow. There is no need to replace one bad solution with another bad solution, creating more work and ripples around. 😉 

The way it would be proper is to allocate systen-wide port from a range, check it of course, and then store its number in either a file somewhere in `/run/...` or (for RO systems) take it already from a `/proc/...` which is exposed and allocated already by own module.

I still don't get why not make a first half of it: just allocate a port system-wide, check if it is free and store in a file. Then next time increment it with a next process.

2023-08-24 09:47 UTC, isbm requested changes

2023-08-24 10:39 UTC, schaefi commented on firecracker-pilot/src/firecracker.rs
> +    let port = defaults::FIRECRACKER_VSOCK_PORT_START + id();
Well what you are saying doesn't make much sense to me and is also not correct.

1. The design mistake in the first place was a random port range and that has to go away. There were two mistakes here, random and range, you don't want to have anything of it. The port that we need here is very much comparable to the process id of a process in Linux and we don't want to be limited by either a range or the problem of random not being random

>  If I expect port range from 4000 to 4010, which is a perfect and valid request

This is not true, that request is wrong by design, nobody wants that. It would be the same like saying start my process but only if Linux assigns me a process ID between 2 and 4 otherwise fail. Sounds very bad to me

> That means as I have now long running machine with PIDs of 820000+, this will also not work

Not true, it's just a number. And as you will not believe me I have tested it by doing something like

```let port = defaults::FIRECRACKER_VSOCK_PORT_START + id() + 820000;```

and running the flake leading to:

```
 ls -l /run/sci_cmd_mybash.sock*
srwxr-xr-x 1 root root 0 Aug 24 12:28 /run/sci_cmd_mybash.sock
srwxr-xr-x 1 root root 0 Aug 24 12:28 /run/sci_cmd_mybash.sock_900516
```

which is perfectly fine as there is no number limitation.

Last but not least the only limit we hit is the number of simultaniosly open UDS ports, which is a limit by the system and not in control of flake-pilot, just accept it

@Ichmed already made the point the looping over files is slow and also racy and the current implementation only has the issue that if some other process (not a flake) uses the same port we hit a conflict.

I'm running with this patch and have done script tests running more than 1000 processes in a resume type firecracker flake without hitting any port issue. However with the former implementation I hit exactly the issue that @m-kat described, getting the same "random" numbers again, and with my former implementation reading the port from the socket file and do a +1 I hit the race condition when two calls does it on the same time.

So what's implemented here is the easiest and stablest version that I could come up with so far

I don't see any reason why it will produce any harm

2023-08-25 11:19 UTC, schaefi commented on firecracker-pilot/src/firecracker.rs
> +    let port = defaults::FIRECRACKER_VSOCK_PORT_START + id();
ok I think I should also clarify on one aspect as people are still talking about port ranges. On the host the pilot is UNIX-LISTEN to a domain socket file, e.g ```/run/sci_cmd_mybash.sock_128000``` the number of the port in the filename has no restrictions. On the guest the the connect is based on a VSOCK (not UDS). So in the guest it's VSOCK-CONNECT:2:128000 for this the port number also does not have the UDS restrictions. The transfer of data between the VSOCK and UDS sock on the host is done in firecracker.

Therefore the concerns raised by people about port ranges and stuff do not apply. I recommend you give all this a real world try to get to the same results I have in my testing here locally. It should be relatively straight forward to do this

2023-08-25 11:21 UTC, schaefi commented on firecracker-pilot/src/firecracker.rs
> +    let port = defaults::FIRECRACKER_VSOCK_PORT_START + id();
From that perspective I have added another commit which allows us to select a specific port number for the very unlikely case that inside of the guest the connected VSOCK port is occupied elsewhere. This should be sufficient in my eyes.

2023-08-27 22:12 UTC, isbm commented on firecracker-pilot/src/firecracker.rs
> +    let port = defaults::FIRECRACKER_VSOCK_PORT_START + id();
> This is not true, that request is wrong by design, nobody wants that.
> It would be the same like saying start my process but only if Linux
> assigns me a process ID between 2 and 4 otherwise fail. Sounds very bad to me

I think I get where I was completely confused from the beginning: the variable name is wrong and the terminology is used. It is not about _ports_ (TCP/network), but about just unique Unix socket files 🤦🏼, as I thought what will happen if we exceed 0xffff. Therefore yes, that would basically do.

Except why reinventing the wheel, instead of just use [tempfile](https://docs.rs/tempfile/latest/tempfile/) or [named tempfile](https://docs.rs/tempfile/latest/tempfile/struct.NamedTempFile.html)?

2023-08-28 07:52 UTC, schaefi commented on firecracker-pilot/src/firecracker.rs
> +    let port = defaults::FIRECRACKER_VSOCK_PORT_START + id();
ok, good. So let's go ahead with this one then. The issue you mentioned about tmpfiles is not clear to me as the code changes here doesn't make use of it. Anyway I think that can be clarified in follow up PRs. So let's get that fix merged. Thanks

2023-08-28 07:56 UTC, merged

2023-08-28 07:56 UTC, isbm commented on firecracker-pilot/src/firecracker.rs
> +    let port = defaults::FIRECRACKER_VSOCK_PORT_START + id();
But we already [use tempfile](https://github.com/Elektrobit/flake-pilot/blob/master/flake-ctl/src/firecracker.rs#L27). 😉 So I still fail to understand why we have to generate these filenames ourselves, if tempfile supposed to make it safely (i.e. ensure no overlaps).

@Ichmed ?