Flake ctl 2
Elektrobit/flake-pilot pull request #166
Opened 2023-09-07 09:25 UTC by Ichmed

same as #164 but without the fork

2023-09-07 10:19 UTC, Ichmed commented
I will delete the old flake-ctl right before the merge

2023-09-10 13:47 UTC, isbm requested changes
I was reviewing-reviewing, but then from the code below I realised this is just moved code 🤣 :

```rust
￼    let mut program_name = String::new();
￼    program_name.push_str(
￼        Path::new(program_path)
￼            .file_name()
￼            .unwrap()
￼            .to_str()
￼            .unwrap(),
￼    );
￼    program_name
￼}
```

Therefore I would:
- Ensure Robot CI for it takes care of `flake-ctl` v1 as "functionality carbon copy", i.e. new `flake-ctl` should never fail any of these tests ever.
- Drop the whole `flake-ctl` v1 and let it R.I.P.
- Update Clap to the latest 1.66.1 compatible
- Merge this

2023-09-10 13:47 UTC, isbm commented on Cargo.toml
> +    "flake-ctl-v1",
Probably not. I would entirely drop old `flake-ctl` in a whole. The only thing that we need to probably write robot tests for it and make sure the v2 is backward-compatible, but that's all.

2023-09-10 13:47 UTC, isbm commented on Makefile
> +	install -m 644 flake-ctl-v1/template/firecracker-flake.yaml \
See above. I would just drop v1 `flake-ctl` and forget it as a good start, but not the best continuation. 😉

2023-09-10 13:47 UTC, isbm commented on flake-ctl/flake-ctl-firecracker/Cargo.toml
> +clap = { version = "3.0.14", features = ["derive"] }
I would _strongly_ recommend migrate to 4.x version, as it is not backward-compatible anymore. Last working on 1.66.1 (needed by Ubuntu LTS 22.04) is 4.3.24, which has all major bugs in 3.x fixed (builder ordering etc) as well as has tons of new nice features.

2023-09-10 13:47 UTC, isbm commented on flake-ctl/flake-ctl-firecracker/src/app.rs
> +        return false;
I am curious why to take this pattern. instead of return `Result<(), std::io::Error>` instead. This function's job is try to register an app and return the result for _further_ processing. Because some outer mechanism should decide what to do: `warn!` it, or panic, how to properly panic etc. Maybe someone wants to send an email if `register()` fails. But then you will get a spaghetti: `error!()` does something here, then somewhere outside this `bool` is checked etc.

I would prefer return results and skip to take care what to do with the error in this function instead, but rather let it be processed somewhere else, in a dedicated place, which can be then configured accordingly.

Thoughts? @m-kat ?

2023-09-10 13:47 UTC, isbm commented on flake-ctl/flake-ctl-firecracker/src/app.rs
> +        }
See the comment above about this design (`error!` vs `Result<T, E>`).

2023-09-10 13:47 UTC, isbm commented on flake-ctl/flake-ctl-firecracker/src/app.rs
> +}
Doesn't look like `rustfmt.toml` works here 😉 Could you double-check?

2023-09-10 13:47 UTC, isbm commented on flake-ctl/flake-ctl-firecracker/src/app.rs
> +                }
Again, you could avoid this monstrosity if just `remove` would return a `Result<T, E>`. Even `match` here is not needed, but still `fs::remove_file(app)?;` should just do.

2023-09-10 13:47 UTC, isbm commented on flake-ctl/flake-ctl-firecracker/src/app.rs
> +                }
😉

2023-09-11 12:12 UTC, Ichmed commented on flake-ctl/flake-ctl-firecracker/Cargo.toml
> +clap = { version = "3.0.14", features = ["derive"] }
4.3.24 already requires clap_derive 4.4.2 which requires rust 1.70

2023-09-13 10:24 UTC, isbm approved these changes
LGTM!

2023-09-13 10:24 UTC, merged