Error handling firecracker
Elektrobit/flake-pilot pull request #170
Opened 2023-09-12 08:41 UTC by Ichmed

Moved all error types to common code
Added proper error handling to firecracker

Sorry for the huge PR, we can split of moving the error types if needed but the large changes to firecracker.rs can no really be reduced in size.

2023-09-13 15:16 UTC, isbm requested changes
@Ichmed  Could you look at these?

2023-09-13 15:16 UTC, isbm commented on common/src/error.rs
> +    AccessDenied,
Uhm... It is not "root priviledges needed", it is "Access denied" 😉 So maybe it makes sense then add `InsufficientPriviledges` instead. And also message "insufficient priviledges". Because it is not necessarily must be `root`, can be also `wheel` and similar ☝️

2023-09-13 15:16 UTC, isbm commented on common/src/error.rs
> +                None => ExitCode::FAILURE,
I would prefer stick to [Unix sysexits](
https://man.freebsd.org/cgi/man.cgi?query=sysexits&apropos=0&sektion=0&manpath=FreeBSD+4.3-RELEASE&format=html). There is a [crate for it](https://github.com/benwilber/exitcode).

2023-09-13 15:16 UTC, isbm commented on common/src/user.rs
> +    user.run("mkdir").arg("-p").arg("-m").arg(mode).arg(dirname).perform()?;
`.arg("-pm")` would do.

2023-09-13 15:16 UTC, isbm commented on firecracker-pilot/src/main.rs
> +        Ok(()) => ExitCode::SUCCESS,
I would use `errorcode::OK` to keep it Unix-"kosher". 😉

2023-09-13 15:16 UTC, isbm commented on firecracker-pilot/src/main.rs
> +            error!("{err}");
Comment only: we need a proper logging, but this...

2023-09-13 16:26 UTC, Ichmed commented on common/src/error.rs
> +                None => ExitCode::FAILURE,
A `None` in this case means the proces was terminated by a signal#, which will a) probably not happen and b) what code would we return here other than generic failure?

If the actual `Command` returns any exit code it will be in the `Some` branch

2023-09-13 16:28 UTC, Ichmed commented on firecracker-pilot/src/main.rs
> +        Ok(()) => ExitCode::SUCCESS,
That should be mapped to the same value (0) when compiled for *nix but still be valid on any other platform so I see no need to change it here.

2023-11-30 10:45 UTC, isbm commented
@Ichmed what's the status here? Do we need this or we can close it?

2023-11-30 13:26 UTC, Ichmed commented
Code has diverged to far, easier to do this again then to merge

2023-11-30 13:26 UTC, closed without merging