Packaging-RfC
Elektrobit/flake-pilot pull request #173
Opened 2023-09-13 16:09 UTC by Ichmed

2023-09-13 16:14 UTC, Ichmed commented
These are just my initial ideas on how to create forward and 3rd party compatible packaging, please feel free to comment @isbm and @m-kat

2023-09-15 08:22 UTC, isbm commented
Yes!

I actually had similar ideas. Except I would call it `flake-build` and add more stuff to it. 😉 However it would involve other tooling, like [Buildah](https://buildah.io), then packaging interface (dpkg, rpmbuild, at some point most likely opkg used by Yocto etc) and even more.

Also I have in mind integrating Buildah with [Mezzotint](https://github.com/isbm/mezzotint) (once it works 🤣) and add some profiling system. And then where it gets a bit bumpy: every time you have parameters involved that turns into YAML, then you have more and more declarative configs that requires more and more coding.

But essentially, `flake-build` profile should:
- Define what is it: VM, OCI, NPK etc
- Define what engine/runtime is used (podman, runc, youki, wasm, fcracker etc)
- Say from which package it is "flaked" into (yes, original software expected to be packaged first)
- other stuff

With "other stuff" could be also a bit interesting:
- Mezzotint can be used: it throws away from a container everything it thinks is a never used junk on a disk.
- Layering and delta containers
- launch wrapper that can enforce parameters, configuration and environment to the software, fully controlling outside input
- etc

So this won't be just a `ctl`. I more see it as a separate subproject, which won't be that simple in a long run. But surely we can start from something trivial, like wrapping whatever stuff into a flake, resulting a Debian package for now.

2023-09-15 08:36 UTC, isbm requested changes

2023-09-15 08:36 UTC, isbm commented on doc/RFC/RfC-0002-automated-packaging.md
> +There will be a flake-ctl tool addon for each kind of package, e.g. `flake-ctl-pkg-deb` or `flake-ctl-pkg-rpm`.
These are rather more like just a trait implementations. And they are essentially callers of whatever package software builder is underneath (rpmbuild or dpkg etc).

Besides I am not sure I want to maintain all of them. If you split that into a different subprograms, then you are raising maintenance efforts by orders of magnitude, because if a feature appears, you will have to add it all over again separately everywhere, _porting_ it. And if Hans is looking after `pkg-deb` and Fred after `pkg-rpm` but they don't talk to each other, you will end up with a flake build that is inconsistent.

2023-09-15 08:36 UTC, isbm commented on doc/RFC/RfC-0002-automated-packaging.md
> +Pilots need to bundle their packaging information somehow
`somehow.unwrap()` it please, otherwise in RFC is not the best design explanation. 😉

2023-09-15 08:36 UTC, isbm commented on doc/RFC/RfC-0002-automated-packaging.md
> +This tool will be maintained independently.
Tool**s**, in this particular RFC proposal.

2023-09-15 08:36 UTC, isbm commented on doc/RFC/RfC-0002-automated-packaging.md
> +  I see no benefit in using `flake-ctl` to register/remove the flakes. Instead the YAML can simply be provided and removed by the package.
The system of symlinking is also needed to be handled.

2023-09-20 11:28 UTC, Ichmed commented on doc/RFC/RfC-0002-automated-packaging.md
> +  I see no benefit in using `flake-ctl` to register/remove the flakes. Instead the YAML can simply be provided and removed by the package.
I created a .deb package that successfully installs a flake without using flake-ctl here
https://ebs.ebgroup.elektrobit.com/package/show/home:mime275136/aarch64-unknown-linux-gnu-gcc

important part, in case the link dies:
```
%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT/usr/share/flakes
mkdir -p $RPM_BUILD_ROOT/tmp
cp %{name}.yaml $RPM_BUILD_ROOT/usr/share/flakes/
cp %{name}.d $RPM_BUILD_ROOT/usr/share/flakes/ -r
cp %{name}.tar.gz $RPM_BUILD_ROOT/tmp

%post
podman load < /tmp/%{name}.tar.gz
ln -s %{_bindir}/podman-pilot %{_bindir}/aarch64-unknown-linux-gnu-gcc

%postun
rm %{_bindir}/aarch64-unknown-linux-gnu-gcc

%clean
rm -rf $RPM_BUILD_ROOT

%files
/tmp/%{name}.tar.gz
/usr/share/flakes/%{name}.yaml
/usr/share/flakes/%{name}.d
```

2023-09-27 14:27 UTC, isbm submitted a review, later dismissed

2023-09-28 07:59 UTC, Ichmed commented on doc/RFC/RfC-0002-automated-packaging.md
> +There will be a flake-ctl tool addon for each kind of package, e.g. `flake-ctl-pkg-deb` or `flake-ctl-pkg-rpm`.
I will create a trait for them so they are forced to follow a common interface, but i would much prefer having them as standalone executables so people can write packagers for other packagers in the language of their choice

2023-09-28 08:32 UTC, isbm approved these changes

2023-09-28 08:32 UTC, merged