Initial flake builder
Elektrobit/flake-pilot pull request #182
Opened 2023-10-05 13:17 UTC by Ichmed

Initial proposal for a flake builder utility

Major Missing features:
- build directly from package
- infer variables from config/package
- multiple pilot symlinks

2023-10-05 13:18 UTC, Ichmed commented
To build run with `--template jflake-ctl/flake-ctl-buikd-debbuild/templates` or copy the contents of that folder to `/usr/share/flakes/package/debbuild`

2023-10-06 12:33 UTC, isbm requested changes
@Ichmed could you take a look at these?

2023-10-06 12:33 UTC, isbm commented on flake-ctl/flake-ctl-build-debbuild/src/debbuild.rs
> +        let template = template.replace("%{_flake_pilot}", config.engine().pilot());
Nice COBOL programming, but this asks for a loop. 😉 

```rust
for (tpl, val) in vec![("%{_flake_name}", &options.name),
                       ("%{_flake_version}", &options.version)] {
    template = template.replace(tpl, val);
}
```

2023-10-06 12:33 UTC, isbm commented on flake-ctl/flake-ctl-build-debbuild/src/debbuild.rs
> +        let template = template.replace("%{_flake_requires}", &requires);
That could be moved to that loop and the `requires` could be calculated earlier. Otherwise spaghetti.

2023-10-06 12:33 UTC, isbm commented on flake-ctl/flake-ctl-build-debbuild/templates/template.spec
> +cp usr/share/flakes/%{name}.d $RPM_BUILD_ROOT/usr/share/flakes/ -r
I would also take these paths (`/usr/share/flakes` in particular) [from the config](https://github.com/Elektrobit/flake-pilot/blob/master/common/src/config/mod.rs#L13) instead (yes, a part of that anti-COBOL loop above).

2023-10-06 12:33 UTC, isbm commented on flake-ctl/flake-ctl-build/src/lib.rs
> +            self.cleanup(&location)?;
But you already called it few lines above anyway?

2023-10-06 12:33 UTC, isbm commented on flake-ctl/flake-ctl-podman/src/podman.rs
> +    let config = load_from_name(&Path::new("/usr/share/flakes").join(flake)).context("failed to read flake config")?;
Nope. Please do not hardcode stuff, but [get from the config](https://github.com/Elektrobit/flake-pilot/blob/master/common/src/config/mod.rs#L13) instead. And in the conf it is already a `PathBuf` for you. 😉

2023-10-06 12:35 UTC, Ichmed commented on flake-ctl/flake-ctl-build/src/lib.rs
> +            self.cleanup(&location)?;
The one above is to make sure the env is clean for the build, this one is to remove the build data

2023-10-06 12:36 UTC, isbm commented on common/src/config/mod.rs
> +pub fn load_from_name(app_p: &Path) -> Result<FlakeConfig, Error> {
Also please move this func as a part of `common/config` so `flakes::load_by_name()` would be also an option in case any other part of this system will need that.

2023-10-06 12:39 UTC, Ichmed commented on flake-ctl/flake-ctl-build-debbuild/src/debbuild.rs
> +        let template = template.replace("%{_flake_pilot}", config.engine().pilot());
no need for the vec, but done

2023-10-06 12:39 UTC, isbm commented on common/src/config/mod.rs
> +pub fn load_from_name(app_p: &Path) -> Result<FlakeConfig, Error> {
This a bit conceptually odd. Seems `app_p` is a target, so `load_by_target` would be a better name. Because `load_from_name` I would literally expect `&str`.

2023-10-09 16:01 UTC, isbm commented on flake-ctl/flake-ctl-build/src/lib.rs
> +            self.cleanup(&location)?;
Hmm, I see, but from the consistency perspective that looks like a mess on its own. 😉 Split the method to two and then call a submethod first?..

2023-10-09 16:03 UTC, isbm requested changes
@Ichmed could you please look at that?

2023-10-09 16:03 UTC, isbm commented on flake-ctl/flake-ctl-podman/src/podman.rs
> +    let config = load_from_target(&config::FLAKE_DIR.join(flake)).context("failed to read flake config")?;
Not that config... [This one](https://github.com/Elektrobit/flake-pilot/tree/master/common/src/config). Wondering why do we have so many local configs. I think they need to go away.

2023-10-12 15:42 UTC, isbm requested changes

2023-10-12 15:42 UTC, isbm commented on flake-ctl/flake-ctl-build/src/lib.rs
> +            self.cleanup(&location)?;
Well, OK. How about rename this to `purge_location()` and have a comment on top if it why it is called? It will kind of mean to anyone that a certain location is simply killed.

You setting up the whole location again, so it makes sense, but maybe make it more visible with an empty line and a comment on top of `setup()`.

2023-10-24 13:41 UTC, isbm requested changes
@Ichmed could you please look at these? It also has conflicts, please rebase.

2023-10-24 13:41 UTC, isbm commented on flake-ctl/flake-ctl-build-rpmbuild/src/main.rs
> +    #[arg(long, default_value = "/usr/share/flakes/package/rpmbuild")]
Hmm. Shouldn't it be in the global config, instead? Yes, it should be. :-)

2023-10-24 13:41 UTC, isbm commented on flake-ctl/flake-ctl-build-rpmbuild/src/main.rs
> +        let config_path = Path::new("/usr/share/flakes").join(name);
Global config, instead? I mean, now there is only for runtime flakes, but at least we can define all these constants there, and in a future (if needed) redefine these in `/etc/flakes.conf` or so.

2023-10-24 13:41 UTC, isbm commented on flake-ctl/flake-ctl-build-rpmbuild/src/main.rs
> +        let fake_flake_dir = bundling_dir.join("usr/share/flakes");
Now it is even worse hardcoding. 😉 I would do something like:

```rust
let ffd = bundling_dir.join(config_path.to_string_lossy().trim_start_matches("/"));
```

...and I would grab `config_path` from the central config instead hardcoding stuff here.

2023-10-24 13:41 UTC, isbm commented on flake-ctl/flake-ctl-podman/src/podman.rs
> +        .arg("-o")
Why it all can't be stored to `.args` and one go?

2023-10-25 08:55 UTC, Ichmed commented on flake-ctl/flake-ctl-podman/src/podman.rs
> +        .arg("-o")
No reason, oi just kept those two on one line because they belong together, but you can't have multiple args with different types on one line so the others aren't

2023-10-25 08:57 UTC, Ichmed commented on flake-ctl/flake-ctl-build-rpmbuild/src/main.rs
> +        let fake_flake_dir = bundling_dir.join("usr/share/flakes");
already resolved in merged branch

2023-10-25 15:55 UTC, isbm approved these changes
LGTM!

2023-10-25 15:55 UTC, merged