Flake-ctl-build-debbian
Elektrobit/flake-pilot pull request #184
Opened 2023-10-09 15:24 UTC by Ichmed

2023-10-09 15:53 UTC, isbm requested changes
@Ichmed could you please look at these ~disasters~ discrepancies? :-)

2023-10-09 16:10 UTC, Ichmed commented on flake-ctl/flake-ctl-build-dpkg/src/main.rs
> +    #[arg(long, default_value = "/usr/share/flakes/package/dpkg")]
also no spec template here

2023-10-12 15:37 UTC, isbm requested changes
I am not entirely convinced of mere existence of [this whole thing](https://github.com/Elektrobit/flake-pilot/blob/85d054d48caa1fcfa8d9b150f6c16eb24dfcf2e3/flake-ctl/flake-ctl-firecracker/src/defaults.rs#L24-L41). I still believe that this should be using (or extending if something is still missing) the central config instead.

2023-10-16 13:47 UTC, Ichmed commented
> I am not entirely convinced of mere existence of [this whole thing](https://github.com/Elektrobit/flake-pilot/blob/85d054d48caa1fcfa8d9b150f6c16eb24dfcf2e3/flake-ctl/flake-ctl-firecracker/src/defaults.rs#L24-L41). I still believe that this should be using (or extending if something is still missing) the central config instead.

Is that referenced somewhere? otherwise i agree but that should not be done in this PR

2023-10-24 12:59 UTC, isbm approved these changes
@Ichmed OK, fine. Let's incorporate `defaults.rs` outdated stuff with the new config in the next PR. Good to go here.

2023-10-25 08:22 UTC, merged