Fix flake-pilot build errors
Elektrobit/flake-pilot pull request #187
Opened 2023-10-18 12:09 UTC by AymenOtt

Building flake-pilot using spec file does not work.
. New common directory missing in the Makefile
. New config template naming updated
. Error related anstyle-parse, does not build with latest version of anstyle-parse > 0.2.1
. Subcommand flake-ctl podman is not available due to missing bins

2023-10-19 09:41 UTC, isbm approved these changes
LGTM

2023-10-19 09:46 UTC, Ichmed commented on Makefile
> +	install -m 644 common/tests/data/cfg-v1/* \
Why is this taken from a test directory? That can not be right.

If this file is required it needs to be provided from somewhere else.

2023-10-19 11:41 UTC, isbm commented on Makefile
> +	install -m 644 common/tests/data/cfg-v1/* \
Actually yes, @AymenOtt. Why tests are installed?

2023-10-19 11:41 UTC, isbm requested changes
Test templates are installed?

2023-10-19 12:41 UTC, AymenOtt commented on Makefile
> +	install -m 644 common/tests/data/cfg-v1/* \
those are templates configs files , there were before in /flake-ctl/template and completely disappeared in the latest version , the only location is under common/test/data/cfg with different names

2023-10-19 13:41 UTC, Ichmed commented on Makefile
> +	install -m 644 common/tests/data/cfg-v1/* \
could you please copy them to `flake-ctl/flake-ctl-podman/templates` and `podman-ctl-firecracker` respectively and install them from there if they are still needed? You should never install from a test

2023-10-19 14:19 UTC, AymenOtt commented on Makefile
> +	install -m 644 common/tests/data/cfg-v1/* \
agree ! Done

2023-10-20 13:06 UTC, isbm requested changes
In a package that part might be a bit adjusted 😉

2023-10-20 13:06 UTC, isbm commented on flake-ctl/flake-ctl-firecracker/templates/firecracker.yaml
> +  target_app_path: /highway/to/hell
@AymenOtt wonderful.

2023-10-23 10:16 UTC, isbm approved these changes
@Ichmed LGTM, maybe you can say smth, otherwise pls merge.

2023-10-23 10:20 UTC, isbm commented on flake-ctl/flake-ctl-firecracker/src/defaults.rs
> +    "/etc/flakes/firecracker.yaml";
@Ichmed I am still wondering why the general config is not used here?

2023-10-23 10:21 UTC, Ichmed approved these changes

2023-10-23 10:22 UTC, Ichmed commented on flake-ctl/flake-ctl-firecracker/src/defaults.rs
> +    "/etc/flakes/firecracker.yaml";
Just hasn't been touched since rhen

2023-10-23 10:23 UTC, merged

2023-11-09 15:21 UTC, Ichmed commented
Fixes #189