Flake-studio
Elektrobit/flake-pilot pull request #193
Opened 2023-11-15 14:58 UTC by Ichmed

2023-11-15 16:45 UTC, isbm requested changes
@Ichmed could you look at these?

2023-11-15 16:45 UTC, isbm commented on flake-ctl/flake-ctl-build/src/options.rs
>  fn user_input(name: &str) -> Result<String> {
I am not entirely in agreement here. I think `user_input` should return `Option<String>` rather then `Result<String>` because there is no need to indicate an _error_ of user input. It is either input or no input, but in both cases they are non-erroneous.

2023-11-15 16:45 UTC, isbm commented on flake-ctl/flake-ctl-build/src/options.rs
> +    Ok(buf)
...and so if this function would return just `Option<String>` then no need for `bail!` macro, a simple `return None;` would just do and be more readable (and no need of that explanation commend either 😛 ).

2023-11-15 16:45 UTC, isbm commented on flake-studio/src/build.rs
> +    eprintln!("{} ({})", "Build finished".green().bold(), name);
Probably STDOUT is still a proper channel here.

2023-11-15 16:45 UTC, isbm commented on flake-studio/src/build.rs
> +fn discover_image_builder() -> Result<ImageBuilder> {
The name suggests dangerous heuristics...

2023-11-15 16:45 UTC, isbm commented on flake-studio/src/build.rs
> +        Some("build.sh") => Some(ImageBuilder::Script),
...and here you go.

2023-11-15 16:45 UTC, isbm commented on flake-studio/src/build.rs
> +}
I am not sure if:
- Discovery needed at all
- It should return `Result<ImageBuilder>` instead of `Result<ImageBuilder, Error>`. Because here then we can switch to a manual build method or exit.
- We should hardcode predefined magic names for conventional scripts

I would rather drop this discovery for now and clearly grab an option from the CLI what dockerfile or what script to run in order to build an image.

2023-11-24 16:35 UTC, Ichmed commented on common/src/config/mod.rs
> +    load_from_path(&flake_dir_from(root).join(app_ps))
I just kept that code as it was before

2023-11-24 16:36 UTC, Ichmed commented on common/src/config/mod.rs
> +    match FlakeCfgParser::new(path.with_extension("yaml"), cfg_d_paths)?.parse() {
That's just the builder pattern to add an extension

2023-11-30 10:43 UTC, isbm approved these changes
lgtm

2023-11-30 10:43 UTC, merged