Add spinner to feedback user on progress
Elektrobit/flake-pilot pull request #63
Opened 2023-03-30 19:46 UTC by schaefi

Add a spinner to show progress during provisioning This Fixes #59

2023-03-30 22:04 UTC, isbm commented on podman-pilot/src/podman.rs
> +use spinoff::{Spinner, spinners, Color};
Wait, there is already implemented one? 😆

2023-03-30 22:07 UTC, isbm requested changes

2023-03-30 22:07 UTC, isbm commented on podman-pilot/src/podman.rs
> +                    spinners::Dots, "Provisioning...", Color::Yellow
Maybe "Setting up..." or "First launch preparation..." or similar is better, because it is still an app from user POV, not a server! 😆

2023-03-31 06:47 UTC, schaefi commented on podman-pilot/src/podman.rs
> +use spinoff::{Spinner, spinners, Color};
rust is an awesome language and yes there is a spinner crate, it's marvelous :)

2023-03-31 06:50 UTC, schaefi commented on podman-pilot/src/podman.rs
> +                    spinners::Dots, "Provisioning...", Color::Yellow
Well not so easy. If you have registered the app with "--resume" your text would be correct "First launch prep..." but if the app was registered without --resume or --attach the containers gets started, provisioned, the app runs, the containers shuts down and gets removed. So the chain of tasks depends on how the app was registered. In this case your text would be a misleading. The word "Provisioning" matches what happens in the code at that time but I agree it might not be understood by the user.

Let's have a call today and I show you how it looks like and let's brainstorm and decide for a name while we are talking ok ?

2023-03-31 10:36 UTC, schaefi commented on podman-pilot/src/podman.rs
> +                    spinners::Dots, "Provisioning...", Color::Yellow
ok done and changed according to the conversation. The spinoff crate unfortunately does not support to put it to the right. I checked the code, so let's keep that as is

2023-03-31 10:40 UTC, isbm approved these changes
LGTM!

2023-03-31 10:54 UTC, merged