Initial commit with firecracker-service
Elektrobit/flake-pilot pull request #69
Opened 2023-04-05 08:17 UTC by m-kat

Base skeleton for firecracker-service

2023-04-05 09:58 UTC, schaefi requested changes
Thanks for starting this :+1: Looks good, I added some comments regarding namespace and logging.

2023-04-05 09:58 UTC, schaefi commented on firecracker-service/src/app.rs
> +pub mod app{
I believe you don't need to explicitly namespace ```app``` here as you already moved it into its own source file called ```app.rs```. This would allow you to get rid of the entire block

```rust
pub mod app{
    ...
}
```

If you do so you decide per function about its scope ```pub fn``` and so on. I think it would make it easier if we later decide to refactor code and put code into a Trait (sort of a class). The module namespace will stay the same given through its filename.

I leave it up to you what you prefer. I usually like if the namespace qualification is unique and can be produced in one way only.

2023-04-05 10:01 UTC, schaefi commented
I think we should also agree on a space in the git for ```firecracker-service```. From an organization point of view this will be dedicated to the firecracker pilot in the end. So what about adding it in the git as:

```
firecracker-pilot/
└── firecracker-service/...
```

Thoughts ?

2023-04-06 07:53 UTC, m-kat commented on firecracker-service/src/main.rs
> +        Err(e) => println!("Error, {}", e),
If I will find some better I will first let you know so we can agree which is better, I'm also not a RUST expert, but always it is good to have common solution in the product so I will use what you used at the moment

2023-04-06 07:55 UTC, m-kat commented
> 

I think that this is a good place.

2023-04-07 06:22 UTC, merged