Added doc for sci
Elektrobit/flake-pilot pull request #93
Opened 2023-05-12 08:55 UTC by wintron04

- [ ] desc for interactive flag missing
- [ ] quality check of example

2023-05-12 18:01 UTC, schaefi requested changes
A good start :+1:  see my comments

2023-05-12 18:01 UTC, schaefi commented on doc/sci.rst
> +    + interactive= boolean
please don't mention it for now, this is pointing to an open pull request and if we decide to merge it the docs should follow but documenting an intermediate state often causes some pain.

2023-05-12 18:01 UTC, schaefi commented on doc/sci.rst
> +| interactive          | boolean           |                                  |
same here, please don't mention interactive for now

2023-05-12 18:01 UTC, schaefi commented on doc/sci.rst
> +Marcus Schäfer
This is you not me :)

2023-05-15 12:50 UTC, schaefi commented
@wintron04 you need to rebase your branch with the current master

2023-05-15 15:11 UTC, schaefi commented
@wintron04 I fixed your branch, see details on teams

@wintron04 your pull request has no description, just "added doc for sci" is not enough imho. See my pull request comment for what I had in mind. I know it might sound picky but some extra words helps if we get back to this history at a later point in time. So at least one little sentence in the description what this pull request does is always helpful ;)

Thanks

2023-05-16 06:57 UTC, m-kat requested changes

2023-05-16 06:57 UTC, m-kat commented on doc/sci.rst
> +if provided via the overlay_root=/dev/block_device kernel boot
IMHO it would be good to state that not only this parameter is needed for overlay but also a proper section in the firecracker JSON configuration file,

2023-05-16 06:57 UTC, m-kat commented on doc/sci.rst
> +| run                  | command           | sci will replace initd and       |
it replaces init not initd (which is a daemon for init subsystem)

2023-05-16 06:57 UTC, m-kat commented on doc/sci.rst
> +|overlay_root          | /dev/block_device | if the rootfs is read only       |
maybe it is worth mentioning that all options regarding filesystems and if they are read-only or not are stored in the firecracker JSON configuration file of a certain vm

2023-05-16 08:54 UTC, wintron04 commented on doc/sci.rst
> +if provided via the overlay_root=/dev/block_device kernel boot
@m-kat with examples of the mentioned section? Or would solely the info be enough?

2023-05-19 09:10 UTC, m-kat commented on doc/sci.rst
> +if provided via the overlay_root=/dev/block_device kernel boot
I think the info some small remark would be enough, just to point that this is not the only configuration parameter that you need to set up to make overlay work

2023-05-22 07:14 UTC, m-kat approved these changes
Looks good to me

2023-05-26 10:34 UTC, schaefi approved these changes
ok, this looks good as an initial version :+1:

2023-05-26 10:34 UTC, merged